### ISSUE TITLE
Symfony Console-like nodejs alternative

### ISSUE THREAD

**Issue by ShinDarth** [Loilo/node-symfony-style-console#8]
Hi @Loilo 

this project looks nice and interesting, good job!

Basing on your experience, I was wondering if it would make sense to build a **Symfony  Console**-like framework using TypeScript for allowing developers to create command line applications using the same paradigms that the Symfony Console offers but with ts/js instead of php.

What do you think? If I had to create such framework, it would surely based on 'node-symfony-style-console'.

**Comment by Loilo** [comment]
Thanks for the appreciation. ❤️ 

What exactly do you mean by "Symfony Console"? This package already implements wide parts of Symfony Console's API. What parts do you think would be worth reproducing in JS/TS?

Generally I don't think it'd be worthwhile.
a) There are already several great CLI frameworks out there.
b) PHP and JS are just very different. I found it rather limiting in various cases to port PHP to JS because of PHP's lack of proper concurrency. 

However, I haven't put much thought into that direction. This package is merely a clone of Symfony's CLI surface to make Node commands in Composer scripts look more integrated and visually consistent.

What would your thoughts about this look like?

**Comment by Loilo** [comment]
Well it would probably be useful if Symfony's API had some serious advantages over existing solutions.

Two thoughts why I think this is not the case:
1. Just from plain experience. I've built CLIs in the Symfony framework as well as with Node's yargs (among others)

**Comment by ShinDarth** [comment]
@Loilo thanks a lot for your feedback, very appreciated!

**Comment by Loilo** [comment]
My pleasure. :)
